version: '3.8'

services:
  postgres:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: seccamp
    volumes:
      - ./misc/sql:/docker-entrypoint-initdb.d

  app:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DATABASE_DSN: postgres://postgres:password@postgres:5432/seccamp
    command: ["/app/wait-for-it.sh", "postgres:5432", "--", "./server"]