apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: melonattacker/go-app-server:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_DSN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DATABASE_DSN
        command: ["/app/wait-for-it.sh", "postgres:5432", "--", "./server"]